### ISSUE TITLE
mapStateToProps() in Connect() must return a plain object. Instead received undefined

### ISSUE THREAD

**Issue by ghost** [Yasser-G/react-native-redux#1]
Hello
After initiating the Provider, I connected one of my components with connect () then I had this error: https://prnt.sc/qxzis1

I initiated my initialState with nothing in it.

Thanks.

**Comment by Yasser-G** [comment]
Hello @Arwantys 

Please make sure you are using the latest version, then try again.
If this issue still happening please provide me with your code showing your `connect` function in use.

Thanks.

**Comment by ghost** [comment]
I already have the latest version.

My index.js

const myInitialState = {}

`<Provider
                initialState={myInitialState}
                loading={<View style={{justifyContent: 'center', flex: 1, alignContent:'center', alignItems:'center'}}><Text style={{fontSize: 22}}>Chargement</Text></View>}
            >
                <App/>
            </Provider>`

My LoginScreen

`import React from 'react';
import { View, Text, StyleSheet, StatusBar, Image, TextInput, TouchableOpacity, ImageBackground, Keyboard, KeyboardAvoidingView, I18nManager } from 'react-native';
import { withNavigation } from 'react-navigation';
import { connect, xSetState, getStateForKey, setStateForKey } from "react-native-redux"

class AuthenticationLoginScreen extends React.Component {

    constructor(props) {
        super(props);
    }


    render() {

        const { translate } = this.props.screenProps;

        return (
            <View style={styles.container}>
                
            </View>
        )
    }

}

export default connect(withNavigation(AuthenticationLoginScreen));`

**Comment by Yasser-G** [comment]
Thank you for providing this issue, 
you can now test latest version after fixing connect function in 68efcfb
 
If this issue still happening feel free to reopen it anytime.
Thanks.
