### ISSUE TITLE
setStateForKey : TypeError: key.includes is not a function. (In 'key.includes('/')', 'key.includes' is undefined

### ISSUE THREAD

**Issue by ghost** [Yasser-G/react-native-redux#2]
Hello,
When using setStateForKey I get an error: https://gyazo.com/b6b0db8b6222b1b504190b355f6c9d54

However xSetState works perfectly. Perhaps I am using the setStateForKey function incorrectly?

`class AuthenticationLoginScreen extends React.Component {

    constructor(props) {
        super(props);
        
    }

    handleLogin = () => {
        setStateForKey("user", { id: 1, name: "Some Name" })
    };

    render() {

        return (
            <View style={styles.container}>
                <SafeAreaView><Text>{this.props.user.name}</Text></SafeAreaView>
                <TouchableOpacity onPress={() => this.handleLogin()}>
                    <Text>test</Text>
                </TouchableOpacity>
            </View>
        )
    }

}

export default connect(withNavigation(AuthenticationLoginScreen));`

Thank

**Comment by Yasser-G** [comment]
@Arwantys Thanks for raising this issue, it is now fixed.
Please note that `xSetState` is most recommended way to set / change state, however using `setStateForKey` is  a most preferred way for changing deep states
